spring:
    #数据源连接池配置
    datasource:
        #默认库
        default:
            username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/xmodule?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true&useCursorFetch=true
        #商品库
        product:
            username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/cg_product?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true&useCursorFetch=true

#swagger配置
springdoc:
    #skip-unannotated-apis: false
    #是否启用API-DOCS(默认/v3/api-docs)
    api-docs:
        enabled: true
    #是否启用Swagger-UI(默认/swagger-ui.html)
    swagger-ui:
        enabled: true